# Generated by Django 5.2.1 on 2025-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='parent', max_length=10),
        ),
    ]
