# Generated by Django 5.2.1 on 2025-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest_app', '0004_subject_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Not applicable'), (2, 'Very easy'), (3, 'Quite easy'), (4, 'Normal'), (5, 'Quite hard'), (6, 'Very hard')]),
        ),
    ]
