# Generated by Django 5.2.1 on 2025-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest_app', '0005_alter_preference_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Very easy'), (2, 'Quite easy'), (3, 'Normal'), (4, 'Quite hard'), (5, 'Very hard')]),
        ),
    ]
