# Generated by Django 5.2.1 on 2025-05-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest_app', '0007_alter_customuser_options_task_points_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('biology', 'Polish Language'), ('chemistry', 'English Language'), ('physics', 'History'), ('history', 'Science'), ('geography', 'Computer Science')], max_length=50, unique=True),
        ),
    ]
