# Generated by Django 5.2.1 on 2025-05-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest_app', '0008_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('polish_language', 'Polish Language'), ('english_language', 'English Language'), ('history', 'History'), ('science', 'Science'), ('computer_science', 'Computer Science')], max_length=50, unique=True),
        ),
    ]
